services:
  postgres:
    image: postgres:16
    container_name: dashbuilder-postgres
    restart: never
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:Z

volumes:
  pg-data: